SECONDS_IN_MINUTES = 60

MINUTES_IN_HOUR = 60
SECONDS_IN_HOUR = MINUTES_IN_HOUR * SECONDS_IN_MINUTES

HOURS_IN_DAY = 24
MINUTES_IN_DAY = HOURS_IN_DAY * MINUTES_IN_HOUR
SECONDS_IN_DAY = MINUTES_IN_DAY * SECONDS_IN_MINUTES